[package]
name = "economy_sim"
version = "0.1.0"
authors = ["Adam H <Roboadam@users.noreply.github.com>"]
edition = "2018"

[dependencies]
macroquad = "0.3.6"
rand = "0.8.4"

[[bin]]
name = "economy_sim"
path = "src/main.rs"
