[package]
name = "economy_sim"
version = "0.1.0"
authors = ["Adam H <Roboadam@users.noreply.github.com>"]
edition = "2018"

[dependencies]
macroquad = "0.3.7"
rand = "0.8.4"
ron = "0.6.4"
serde = "1.0.127"

[[bin]]
name = "economy_sim"
path = "src/main.rs"
